title: "Parallel Programming in Climate and Weather"
author: "CLEX CMS"
repository:
    url: https://github.com/coecms-training/parallel
html:
    use_repository_button: true
execute:
    execute_notebooks: "off"
